/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import app.Principal;
import dweller.Person;
import exceptions.DadosPessoaisIncompletosException;
import exceptions.CategoriaNaoInformadaException;
import exceptions.DescricaoNaoInformadaException;
import exceptions.ValorNaoInformadoException;
import files.FileHandler;
import household.Republic;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.LinkedList;
import expenditure.Category;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author guilherme
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Republic republic;
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        Root = new javax.swing.JPanel();
        homeCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formPerson = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameEntry = new javax.swing.JTextField();
        emailEntry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        incomeEntry = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        formEditPerson = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newIncome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        namesList = new javax.swing.JList<>();
        formDeletePerson = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        namesDeleteList = new javax.swing.JList<>();
        formCategory = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        descEntry = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        comboSubs = new javax.swing.JComboBox<>();
        formSubCategory = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        subEntry = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        formCost = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        costDesc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        valueEntry = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        categoryEntry = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadButton = new javax.swing.JRadioButtonMenuItem();
        saveButton = new javax.swing.JRadioButtonMenuItem();
        exportTxt = new javax.swing.JRadioButtonMenuItem();
        newMenu = new javax.swing.JMenu();
        homeButton = new javax.swing.JRadioButtonMenuItem();
        newPersonButton = new javax.swing.JRadioButtonMenuItem();
        newCategoryButton = new javax.swing.JRadioButtonMenuItem();
        newSubCategoryButton = new javax.swing.JRadioButtonMenuItem();
        newCostButton = new javax.swing.JRadioButtonMenuItem();
        editMenu = new javax.swing.JMenu();
        editPerson = new javax.swing.JRadioButtonMenuItem();
        deleteMenu = new javax.swing.JMenu();
        deletePerson = new javax.swing.JRadioButtonMenuItem();
        showMenu = new javax.swing.JMenu();
        showDwellers = new javax.swing.JRadioButtonMenuItem();
        showCosts = new javax.swing.JRadioButtonMenuItem();
        showCategories = new javax.swing.JRadioButtonMenuItem();
        showSubCategories = new javax.swing.JRadioButtonMenuItem();
        showRulesIg = new javax.swing.JMenuItem();
        showRulesProp = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        Root.setBackground(new java.awt.Color(226, 242, 243));
        Root.setLayout(new java.awt.CardLayout());

        homeCard.setBackground(new java.awt.Color(226, 242, 243));
        homeCard.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 108, 103));
        jLabel1.setText("Principal");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout homeCardLayout = new javax.swing.GroupLayout(homeCard);
        homeCard.setLayout(homeCardLayout);
        homeCardLayout.setHorizontalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        homeCardLayout.setVerticalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeCardLayout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Root.add(homeCard, "home");

        formPerson.setBackground(new java.awt.Color(226, 242, 243));
        formPerson.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 108, 103));
        jLabel2.setText("Adicionar pessoa");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        nameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEntryActionPerformed(evt);
            }
        });

        emailEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEntryActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel5.setText("Renda:");

        jButton1.setBackground(new java.awt.Color(134, 205, 205));
        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPersonLayout = new javax.swing.GroupLayout(formPerson);
        formPerson.setLayout(formPersonLayout);
        formPersonLayout.setHorizontalGroup(
            formPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameEntry)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailEntry)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(incomeEntry))
                    .addComponent(jButton1))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        formPersonLayout.setVerticalGroup(
            formPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Root.add(formPerson, "newPerson");

        formEditPerson.setBackground(new java.awt.Color(226, 242, 243));
        formEditPerson.setName(""); // NOI18N

        jLabel6.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 108, 103));
        jLabel6.setText("Edit Person");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel7.setText("Nome:");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel9.setText("Renda:");

        jButton2.setBackground(new java.awt.Color(134, 205, 205));
        jButton2.setText("Aplicar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel10.setText("Select Person:");

        jButton3.setBackground(new java.awt.Color(134, 205, 205));
        jButton3.setText("Selecionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(134, 205, 205));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        namesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item1", "item2", "item3", "item4", "item5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        namesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(namesList);

        javax.swing.GroupLayout formEditPersonLayout = new javax.swing.GroupLayout(formEditPerson);
        formEditPerson.setLayout(formEditPersonLayout);
        formEditPersonLayout.setHorizontalGroup(
            formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newName)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newEmail)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newIncome))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(formEditPersonLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(formEditPersonLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        formEditPersonLayout.setVerticalGroup(
            formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formEditPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formEditPersonLayout.createSequentialGroup()
                        .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(formEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        Root.add(formEditPerson, "editPerson");

        formDeletePerson.setBackground(new java.awt.Color(226, 242, 243));
        formDeletePerson.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 108, 103));
        jLabel11.setText("Deletar pessoa");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel15.setText("Selecionar pessoa:");

        jButton6.setBackground(new java.awt.Color(134, 205, 205));
        jButton6.setText("Selecionar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(134, 205, 205));
        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        namesDeleteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item1", "item2", "item3", "item4", "item5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        namesDeleteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(namesDeleteList);

        javax.swing.GroupLayout formDeletePersonLayout = new javax.swing.GroupLayout(formDeletePerson);
        formDeletePerson.setLayout(formDeletePersonLayout);
        formDeletePersonLayout.setHorizontalGroup(
            formDeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDeletePersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDeletePersonLayout.createSequentialGroup()
                        .addGroup(formDeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(formDeletePersonLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formDeletePersonLayout.setVerticalGroup(
            formDeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDeletePersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formDeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        Root.add(formDeletePerson, "deletePerson");

        formCategory.setBackground(new java.awt.Color(226, 242, 243));

        jLabel12.setText("Categoria");

        descEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descEntryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 108, 103));
        jLabel13.setText("Adicionar categoria");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        jLabel17.setText("Subcategoria");

        jButton5.setBackground(new java.awt.Color(134, 205, 205));
        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        comboSubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSubsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formCategoryLayout = new javax.swing.GroupLayout(formCategory);
        formCategory.setLayout(formCategoryLayout);
        formCategoryLayout.setHorizontalGroup(
            formCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addComponent(descEntry))
                    .addComponent(jButton5)
                    .addComponent(comboSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        formCategoryLayout.setVerticalGroup(
            formCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(comboSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        Root.add(formCategory, "newCategory");

        formSubCategory.setBackground(new java.awt.Color(226, 242, 243));

        jLabel14.setText("Subcategoria");

        subEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subEntryActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(31, 108, 103));
        jLabel16.setText("Adicionar subcategoria");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(134, 205, 205));
        jButton8.setText("Adicionar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formSubCategoryLayout = new javax.swing.GroupLayout(formSubCategory);
        formSubCategory.setLayout(formSubCategoryLayout);
        formSubCategoryLayout.setHorizontalGroup(
            formSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSubCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addComponent(subEntry))
                    .addComponent(jButton8))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        formSubCategoryLayout.setVerticalGroup(
            formSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSubCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        Root.add(formSubCategory, "newSubCategory");

        formCost.setBackground(new java.awt.Color(226, 242, 243));
        formCost.setName(""); // NOI18N

        jLabel18.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(31, 108, 103));
        jLabel18.setText("Add Person");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel19.setText("Descrição:");

        costDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costDescActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel20.setText("Categoria:");

        jLabel21.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel21.setText("Valor:");

        jButton9.setBackground(new java.awt.Color(134, 205, 205));
        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        categoryEntry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formCostLayout = new javax.swing.GroupLayout(formCost);
        formCost.setLayout(formCostLayout);
        formCostLayout.setHorizontalGroup(
            formCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(costDesc)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valueEntry)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(categoryEntry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton9))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        formCostLayout.setVerticalGroup(
            formCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCostLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        Root.add(formCost, "newCost");

        jMenuBar1.setBackground(new java.awt.Color(134, 205, 205));
        jMenuBar1.setBorder(null);

        fileMenu.setForeground(new java.awt.Color(31, 108, 103));
        fileMenu.setText("Arquivo");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        loadButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadButton.setBackground(new java.awt.Color(182, 224, 224));
        loadButton.setText("Carregar");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        fileMenu.add(loadButton);

        saveButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveButton.setBackground(new java.awt.Color(182, 224, 224));
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        fileMenu.add(saveButton);

        exportTxt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exportTxt.setBackground(new java.awt.Color(182, 224, 224));
        exportTxt.setText("Exportar txt");
        exportTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTxtActionPerformed(evt);
            }
        });
        fileMenu.add(exportTxt);

        jMenuBar1.add(fileMenu);

        newMenu.setForeground(new java.awt.Color(31, 108, 103));
        newMenu.setText("Novo");
        newMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuActionPerformed(evt);
            }
        });

        homeButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        homeButton.setBackground(new java.awt.Color(182, 224, 224));
        homeButton.setText("Principal");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        newMenu.add(homeButton);

        newPersonButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newPersonButton.setBackground(new java.awt.Color(182, 224, 224));
        newPersonButton.setText("Nova pessoa");
        newPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPersonButtonActionPerformed(evt);
            }
        });
        newMenu.add(newPersonButton);

        newCategoryButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        newCategoryButton.setBackground(new java.awt.Color(182, 224, 224));
        newCategoryButton.setSelected(true);
        newCategoryButton.setText("Nova categoria");
        newCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCategoryButtonActionPerformed(evt);
            }
        });
        newMenu.add(newCategoryButton);

        newSubCategoryButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        newSubCategoryButton.setBackground(new java.awt.Color(182, 224, 224));
        newSubCategoryButton.setSelected(true);
        newSubCategoryButton.setText("Nova subcategoria");
        newSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubCategoryButtonActionPerformed(evt);
            }
        });
        newMenu.add(newSubCategoryButton);

        newCostButton.setBackground(new java.awt.Color(182, 224, 224));
        newCostButton.setSelected(true);
        newCostButton.setText("Nova despesa");
        newCostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCostButtonActionPerformed(evt);
            }
        });
        newMenu.add(newCostButton);

        jMenuBar1.add(newMenu);

        editMenu.setForeground(new java.awt.Color(31, 108, 103));
        editMenu.setText("Editar");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        editPerson.setBackground(new java.awt.Color(182, 224, 224));
        editPerson.setText("Editar pessoa");
        editPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPersonActionPerformed(evt);
            }
        });
        editMenu.add(editPerson);

        jMenuBar1.add(editMenu);

        deleteMenu.setForeground(new java.awt.Color(31, 108, 103));
        deleteMenu.setText("Deletar");
        deleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuActionPerformed(evt);
            }
        });

        deletePerson.setBackground(new java.awt.Color(182, 224, 224));
        deletePerson.setText("Deletar pessoa");
        deletePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePersonActionPerformed(evt);
            }
        });
        deleteMenu.add(deletePerson);

        jMenuBar1.add(deleteMenu);

        showMenu.setForeground(new java.awt.Color(31, 108, 103));
        showMenu.setText("Exibir");
        showMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMenuActionPerformed(evt);
            }
        });

        showDwellers.setBackground(new java.awt.Color(182, 224, 224));
        showDwellers.setText("Residentes");
        showDwellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDwellersActionPerformed(evt);
            }
        });
        showMenu.add(showDwellers);

        showCosts.setBackground(new java.awt.Color(182, 224, 224));
        showCosts.setText("Despesas");
        showCosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCostsActionPerformed(evt);
            }
        });
        showMenu.add(showCosts);

        showCategories.setBackground(new java.awt.Color(182, 224, 224));
        showCategories.setText("Categorias");
        showCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCategoriesActionPerformed(evt);
            }
        });
        showMenu.add(showCategories);

        showSubCategories.setBackground(new java.awt.Color(182, 224, 224));
        showSubCategories.setText("Subcategorias");
        showSubCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSubCategoriesActionPerformed(evt);
            }
        });
        showMenu.add(showSubCategories);

        showRulesIg.setText("Regras Igualitárias");
        showRulesIg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRulesIgActionPerformed(evt);
            }
        });
        showMenu.add(showRulesIg);

        showRulesProp.setText("Regras Proporcionais");
        showRulesProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRulesPropActionPerformed(evt);
            }
        });
        showMenu.add(showRulesProp);

        jMenuBar1.add(showMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void newMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"home");
    }//GEN-LAST:event_newMenuActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"home");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void newPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPersonButtonActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"newPerson");
    }//GEN-LAST:event_newPersonButtonActionPerformed

    private void showDwellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDwellersActionPerformed
        Principal.republic.showResidents();
    }//GEN-LAST:event_showDwellersActionPerformed

    private void showCostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCostsActionPerformed
        Principal.republic.showCosts();
    }//GEN-LAST:event_showCostsActionPerformed

    private void showMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nameEntry.getText();
        String email = emailEntry.getText();
        String income = incomeEntry.getText();
        
        try {
            Principal.republic.addPerson(name, email, income);
            JOptionPane.showMessageDialog(null, "Cadastro realizado!");
        } catch(DadosPessoaisIncompletosException ex) {
            JOptionPane.showMessageDialog(null, ex.getExceptionMessage());
        }
        
        nameEntry.setText("");
        emailEntry.setText("");
        incomeEntry.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "It will override the actual saved file. Are you sure?");
        
        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            FileHandler.saveObject(Principal.republic, "alunos.bin");
            JOptionPane.showMessageDialog(null, "Saved succefully!");
        } else {
            JOptionPane.showMessageDialog(null, "Aborted!");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        Principal.republic = (Republic) FileHandler.loadObject("alunos.bin");
        JOptionPane.showMessageDialog(null, "Loaded file");
    }//GEN-LAST:event_loadButtonActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void exportTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTxtActionPerformed
        try {
            FileHandler.exportObject(Principal.republic, "alunos.txt");
            JOptionPane.showMessageDialog(null, "Exportado com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Falha na exportação!");
        }
    }//GEN-LAST:event_exportTxtActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        String selected = namesList.getSelectedValue();
        Republic r = Principal.republic;
        LinkedList<Person> residents = r.getResidents();
        int index = namesList.getSelectedIndex();
        if (selected != null) {
            Person p = r.searchPerson(selected);
            String name = newName.getText();
            String email = newEmail.getText();
            String income = newIncome.getText();
            Person newPerson;
            
            try {
                newPerson = new Person(name,email,income);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Insira dados válidos!");
                newName.setText(p.getName());
                newEmail.setText(p.getEmail());
                newIncome.setText(Float.toString(p.getIncome()));
                
                return;
            }
            
            residents.set(index, newPerson);
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma pessoa primeiro!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPersonActionPerformed
        updateList(namesList);
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"editPerson");
    }//GEN-LAST:event_editPersonActionPerformed

    private void updateList(JList lista) {
        DefaultListModel model = new DefaultListModel();
        model.clear();

        for(Person p: Principal.republic.getResidents()) {
            model.addElement(p.getName());
        }
        
        lista.setModel(model);
    }
    
    private void updateCombo(JComboBox combo, String[] names) {
        combo.removeAllItems();
        
        for (String s : names) {
            combo.addItem(s);
        }
    }
    
    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String selected = namesList.getSelectedValue();
        Republic r = Principal.republic;
        if(selected != null) {
            Person p = r.searchPerson(selected);
            newName.setText(p.getName());
            newEmail.setText(p.getEmail());
            newIncome.setText(Float.toString(p.getIncome()));
           
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Pessoa!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"home");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deletePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePersonActionPerformed
        updateList(namesDeleteList);
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"deletePerson");
    }//GEN-LAST:event_deletePersonActionPerformed

    private void deleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMenuActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int index = namesDeleteList.getSelectedIndex();
        if (index != -1) {
            LinkedList<Person> residents = Principal.republic.getResidents();
            residents.remove(index);
            JOptionPane.showMessageDialog(null, "Inquilino removido com sucesso!");
            updateList(namesDeleteList);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um nome!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"home");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void newCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCategoryButtonActionPerformed
        String[] names = Principal.republic.getCategoriesSubs();
        updateCombo(comboSubs,names);
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"newCategory");
    }//GEN-LAST:event_newCategoryButtonActionPerformed

    private void descEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descEntryActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String desc = descEntry.getText();
        int index = comboSubs.getSelectedIndex();
        try {
            Principal.republic.addCategory(desc, index);
            JOptionPane.showMessageDialog(null, "Categoria inserida com sucesso!");
            descEntry.setText("");
            comboSubs.setSelectedIndex(0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Insira um nome pra categoria!");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryActionPerformed

    private void emailEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEntryActionPerformed

    private void newSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubCategoryButtonActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"newSubCategory");
    }//GEN-LAST:event_newSubCategoryButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String desc = subEntry.getText();
        try {
            Principal.republic.addSubCategory(desc);
            JOptionPane.showMessageDialog(null, "Sub categoria cadastrada com sucesso!");
            subEntry.setText("");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Insira uma Sub Categoria!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void subEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subEntryActionPerformed

    private void showCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCategoriesActionPerformed
        Principal.republic.showCategories();
    }//GEN-LAST:event_showCategoriesActionPerformed

    private void showSubCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSubCategoriesActionPerformed
        Principal.republic.showSubCategories();
    }//GEN-LAST:event_showSubCategoriesActionPerformed

    private void newCostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCostButtonActionPerformed
        String[] names = Principal.republic.getCategories();
        updateCombo(categoryEntry, names);
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root,"newCost");
    }//GEN-LAST:event_newCostButtonActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void costDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costDescActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String desc = costDesc.getText();
        int index = categoryEntry.getSelectedIndex();
        String value = valueEntry.getText();
        Category category = Principal.republic.getCategory(index);
        
        try {
            Principal.republic.addCost(desc, category, value);
            JOptionPane.showMessageDialog(null, "Cadastro realizado!");
        } catch (DescricaoNaoInformadaException | CategoriaNaoInformadaException | ValorNaoInformadoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        costDesc.setText("");
        categoryEntry.setSelectedIndex(0);
        valueEntry.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void categoryEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryEntryActionPerformed

    private void comboSubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSubsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSubsActionPerformed

    private void showRulesIgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRulesIgActionPerformed
        // TODO add your handling code here:
//        Principal.republic.showCalculoTotal();
        JOptionPane.showMessageDialog(null, "Valor a pagar para cada Membro: " + Principal.republic.calcularTotal());
    }//GEN-LAST:event_showRulesIgActionPerformed

    private void showRulesPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRulesPropActionPerformed
        // TODO add your handling code here:
        Principal.republic.calculoTotalProporcional();
    }//GEN-LAST:event_showRulesPropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Root;
    private javax.swing.JComboBox<String> categoryEntry;
    private javax.swing.JComboBox<String> comboSubs;
    private javax.swing.JTextField costDesc;
    private javax.swing.JMenu deleteMenu;
    private javax.swing.JRadioButtonMenuItem deletePerson;
    private javax.swing.JTextField descEntry;
    private javax.swing.JMenu editMenu;
    private javax.swing.JRadioButtonMenuItem editPerson;
    private javax.swing.JTextField emailEntry;
    private javax.swing.JRadioButtonMenuItem exportTxt;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel formCategory;
    private javax.swing.JPanel formCost;
    private javax.swing.JPanel formDeletePerson;
    private javax.swing.JPanel formEditPerson;
    private javax.swing.JPanel formPerson;
    private javax.swing.JPanel formSubCategory;
    private javax.swing.JRadioButtonMenuItem homeButton;
    private javax.swing.JPanel homeCard;
    private javax.swing.JTextField incomeEntry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButtonMenuItem loadButton;
    private javax.swing.JTextField nameEntry;
    private javax.swing.JList<String> namesDeleteList;
    private javax.swing.JList<String> namesList;
    private javax.swing.JRadioButtonMenuItem newCategoryButton;
    private javax.swing.JRadioButtonMenuItem newCostButton;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newIncome;
    private javax.swing.JMenu newMenu;
    private javax.swing.JTextField newName;
    private javax.swing.JRadioButtonMenuItem newPersonButton;
    private javax.swing.JRadioButtonMenuItem newSubCategoryButton;
    private javax.swing.JRadioButtonMenuItem saveButton;
    private javax.swing.JRadioButtonMenuItem showCategories;
    private javax.swing.JRadioButtonMenuItem showCosts;
    private javax.swing.JRadioButtonMenuItem showDwellers;
    private javax.swing.JMenu showMenu;
    private javax.swing.JMenuItem showRulesIg;
    private javax.swing.JMenuItem showRulesProp;
    private javax.swing.JRadioButtonMenuItem showSubCategories;
    private javax.swing.JTextField subEntry;
    private javax.swing.JTextField valueEntry;
    // End of variables declaration//GEN-END:variables
}
